image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build
  - test
  - package
  - frontend


# build all
build:
  stage: build
  before_script:
    - apt update -qq
    - apt-get install -qq wget software-properties-common

    # install cmake 3.10
    - wget -q https://cmake.org/files/v3.10/cmake-3.10.0-rc4-Linux-x86_64.sh
    - mkdir /opt/cmake
    - sh cmake-3.10.0-rc4-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
    - ln -s /opt/cmake/bin/cmake /usr/bin/cmake
    - ln -s /opt/cmake/bin/cpack /usr/bin/cpack

    # install other deps
    - apt-get install -qq zlib1g-dev libopenblas-dev liblapack-dev libuv-dev build-essential libssl-dev git python

    # install gcc 7
    - add-apt-repository ppa:ubuntu-toolchain-r/test
    - apt-get update
    - apt install -qq -y g++-7
    - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60  --slave /usr/bin/g++ g++ /usr/bin/g++-7
    - update-alternatives --config gcc

    # tool versions
    - cmake --version
    - g++ --version

  script:
    - mkdir -p cmake-build
    - cd cmake-build
    - cmake ..
    - make -j $(nproc)

  # cache dependencies
  cache:
    key: deps
    paths:
      - cmake-build
      - trainServer/dependencies/mxnet
      - trainServer/dependencies/seasocks

  artifacts:
    name: build_output
    paths:
      - build/
      - cmake-build/
      - trainServer/

frontend:
  stage: frontend
  image: ubuntu:16.04
  dependencies:
    - package
  before_script:
    - apt update -qq
    - apt-get install -qq npm curl
    - curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
    - bash nodesource_setup.sh
    - apt-get install -qq nodejs
    - npm install -g @angular/cli
  script:
    - cd frontend-angular
    - npm install
    - ng build
  cache:
    key: nodeModules
    paths:
      - frontend-angular/node_modules/

# run tests
test:
  stage: test
  dependencies:
    - build
  script:
    - ./build/catflow-test

package:
  stage: package
  dependencies:
    - build
  before_script:
    - apt update -qq
    - apt-get install -qq wget #software-properties-common

    # install cmake 3.10
    - wget -q https://cmake.org/files/v3.10/cmake-3.10.0-rc4-Linux-x86_64.sh
    - mkdir /opt/cmake
    - sh cmake-3.10.0-rc4-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
    - ln -s /opt/cmake/bin/cmake /usr/bin/cmake
    - ln -s /opt/cmake/bin/cpack /usr/bin/cpack

    # install other deps
    #- apt-get install -qq zlib1g-dev libopenblas-dev liblapack-dev libuv-dev build-essential libssl-dev git python

    # install gcc 7
    #- add-apt-repository ppa:ubuntu-toolchain-r/test
    #- apt-get update
    #- apt install -qq -y g++-7
    #- update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60  --slave /usr/bin/g++ g++ /usr/bin/g++-7
    #- update-alternatives --config gcc

    # tool versions
    - cmake --version
    #- g++ --version
  script:
    - cd cmake-build
    - cpack -G DEB -V
    - cpack -G TGZ
  artifacts:
    name: openhabai-install-package
    when: always
    paths:
      - build/pack
      - cmake-build