language: cpp

sudo: required
dist: trusty

notifications:
  slack: pancakesoftware:CGasYWILEycD9hFQ8G2EllhR

cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/deps/cmake
        - ${TRAVIS_BUILD_DIR}/trainServer/dependencies/mxnet

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - sudo apt-get install -qq zlib1g-dev libopenblas-dev liblapack-dev cmake npm nodejs libuv-dev
  - if [[ "$CXX" == clang* ]]; then export CXXFLAGS="-stdlib=libc++"; fi
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ ! -d "$(ls -A ${DEPS_DIR}/cmake)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
  - cd "${TRAVIS_BUILD_DIR}"

before_script:
  - cmake --version
  - cmake .

script:
  - make
  - ./build/bin/catflow-test